name: gtisma
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_facebook_login: ^3.0.0
  flutter_page_transition: ^0.1.0
  introduction_screen: ^1.0.7
  animated_splash_screen: ^1.0.1+2
  google_sign_in: ^4.0.2
  sign_button: ^1.0.1
  http: ^0.12.0+2


  flutter_svg: ^0.19.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.4+6
  google_fonts: ^1.1.1
  firebase_messaging: ^7.0.3
  device_info: ^1.0.0
  flutter_local_notifications: ^0.8.2
  awesome_dialog: ^1.2.1
  connectivity: ^2.0.2
  dio: ^3.0.10
  line_icons: ^0.2.0
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  animate_do: ^1.7.5
  avatar_glow: ^1.2.0
  camera:
  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  floating_action_bubble: ^1.1.2
  flutter_animator_widgets: ^1.0.1
  simple_animations: ^2.4.2
  sprung: ^2.0.1+1
  location: ^3.0.0
  flutter_sound: ^7.5.1+2
  permission_handler: ^5.0.1+1
  just_audio: ^0.6.12

  file: ^5.0.4
  audioplayers: ^0.13.2
  lottie: ^0.7.0+1
  simple_timer: ^1.0.1
  animate_icons: ^1.0.0
  fileaudioplayer: ^1.0.0
  video_player:
  flutter_audio_recorder: ^0.5.5
  get: ^3.4.2
  flutter_paginator: ^0.0.6
  carousel_slider: ^2.3.1
  cached_network_image: ^2.5.0
  jiffy: ^3.0.1
  chewie_audio:





dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_driver:
  chewie:



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/myIcons/
    - assets/images/animated_welcome.json



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
